version: '3.9'

services:
  frontend:
    build: ./Frontend
    container_name: frontend-app
    env_file:
      - ./Frontend/.env
    ports:
      - "80:80"
    depends_on:
      - auth_service
      - post_service
      - user_service
      - comment_service
    networks:
      - fullstack

  auth_service:
    build: ./backend/auth_service
    container_name: auth_service
    env_file:
      - ./backend/auth_service/.env
    ports:
      - "8000:8000"
    networks:
      - fullstack

  post_service:
    build: ./backend/post_service
    container_name: post_service
    env_file:
      - ./backend/post_service/.env
    ports:
      - "8002:8002"
    networks:
      - fullstack

  user_service:
    build: ./backend/user_service
    container_name: user_service
    env_file:
      - ./backend/user_service/.env
    ports:
      - "8001:8001"
    networks:
      - fullstack

  comment_service:
    build: ./backend/comment_service
    container_name: comment_service
    env_file:
      - ./backend/comment_service/.env
    ports:
      - "8003:8003"
    networks:
      - fullstack

networks:
  fullstack: