version: '3.9'

services:
  auth-service:
    build: ./auth_service
    container_name: auth-service
    ports:
      - "8000:8000"
    env_file:
      - ./auth_service/.env
    depends_on:
      - user-service
    networks:
      - backend

  user-service:
    build: ./user_service
    container_name: user-service
    ports:
      - "8001:8001"
    env_file:
      - ./user_service/.env
    networks:
      - backend

  post-service:
    build: ./post_service
    container_name: post-service
    ports:
      - "8002:8002"
    env_file:
      - ./post_service/.env
    depends_on:
      - user-service
      - auth-service
    networks:
      - backend

  comment-service:
    build: ./comment_service
    container_name: comment-service
    ports:
      - "8003:8003"
    env_file:
      - ./comment_service/.env
    depends_on:
      - auth-service
      - post-service
    networks:
      - backend

networks:
  backend:
    driver: bridge